// Generated by CoffeeScript 1.10.0
(function() {
  var gcd;

  gcd = require('views/lib/gcd');

  module.exports = function(upper_bound) {
    var current;
    current = Math.floor(Math.random() * upper_bound);
    while (gcd(upper_bound, current) !== 1) {
      current += 1;
    }
    return current;
  };

}).call(this);
