###########################################################################
#
#  German translation of MoxQuizz' messages
#
#  Translator:  Moxon <moxon@meta-x.de>
#
###########################################################################


###########################################################################
#
# Status messages
#
###########################################################################

#
# initialize
#
mcset de "%sHello!  I am a MoxQuizz version %s and ready to squeeze your brain!" \
         "%sHallo!  Ich bin ein MoxQuizz Version %s, bereit dein Wissen zu testen!"

mcset de "%s%d questions in database, just %s!ask%s.  Report bugs and suggestions to moxon@meta-x.de" \
         "%sDie Datenbank umfasst %d Fragen, los gehts mit %s!ask%s.  Bugs und Anregungen an moxon@meta-x.de"

#
# stopped
#
mcset de "%s %sQuiz stopped." \
         "%s %sQuiz gestopt."

#
# paused
#
mcset de "%s %sQuiz halted.  Say !ask for new questions." \
         "%s %sQuiz angehalten.  Mit !ask gehts weiter."

mcset de "%sQuiz paused%s" \
         "%sQuiz auf Pause%s"

mcset de " after %s." \
         " nach %s."

#
# continue
#
mcset de "%sQuiz continued.  Since there is no open question, a new one will be asked." \
         "%sDas Quiz geht weiter.  Da keine Frage offen war, kommt eine neue."

mcset de "%sQuiz continued.  The question open since %s, worth %d point(s):" \
         "%sDas Quiz geht weiter.  Die seit %s offene Frage (%d Punkt(e)):"

mcset de "%sQuiz continued.  The user question open since %s, worth %d point(s):" \
         "%sDas Quiz geht weiter.  Die seit %s offene User-Frage (%d Punkt(e)):"

#
# exit
#
mcset de "%sI am leaving now, after running for %s."\
         "%sDas Quiz verlässt euch nach %s."

#
# Quiz moved to a new channel
#
mcset de "Quiz is leaving to %s.  Goodbye!"\
         "Das Quiz geht in den Channel %s.  Ciao!"

mcset de "Quiz is now on this channel.  Hello!" \
         "Das Quiz ist nun in diesem Channel.  Hallo!"

mcset de "%s Goodbye." \
         "%s Ciao."


###########################################################################
#
# Messages regarding solved questions and such.
#
###########################################################################


mcset de "%s: since you won %d games in a row, you will be ignored for the next game." \
        "%s: da du %s Spiele in Folge gewonnen hast, musst Du ein Spiel aussetzen."

mcset de "No, you've won the last %d games." \
         "Sorry, Du hast bereits die letzten %d Spiele gewonnen."

mcset de "%s solved after %s and now has %s<%d>%s points (+%d) on rank %d." \
         "%s löst nach %s und hat nun %s<%d>%s Punkte (+%d) auf Platz %d."

mcset de "%sThe answer was:%s%s" \
         "%sDie Lösung war:%s%s"

mcset de "%sThree in a row!" \
         "%sDrei in einer Reihe!"

mcset de "%sCongratulation, five in a row! You receive an extra point." \
         "%sGlückwunsch, Fünf in einer Reihe.  Das gibt einen Extrapunkt."

mcset de "%sTen in a row! This is really rare, so you get 3 extra points." \
         "%sZehn in einer Reihe!  Das ist wirklich selten und gibt 3 Extrapunkte."

mcset de "%sTwenty in a row! This is extremely rare, so you get 5 extra points." \
         "%sZwanzig in einer Reihe! Das ist extrem selten und gibt 5 Extrapunkte."

mcset de "%s%s reaches %d points and wins%s" \
         "%s%s erreicht %d Punkte und gewinnt%s"

mcset de "%sHalftime.  Game is won at %d points." \
         "%sHalbzeit.  Das Spiel ist bei %d Punkten gewonnen."

mcset de "%s%s has 10 points to go." \
         "%s%s braucht nur noch 10 Punkte."

mcset de "%s%s has 5 points to go." \
         "%s%s braucht nur noch 5 Punkte."

mcset de "%s%s has %d point(s) to go." \
         "%s%s braucht nur noch %d Punkt(e)."

mcset de "%s solved own question after %s and gets no points, keeping %s<%d>%s points on rank %d." \
         "%s hat eine eigene Frage nach %s gelöst und bekommt dafür keine Punkte.  Aktuell: %s<%d>%s Punkte auf Rang %d."

mcset de "%sThe answer was:%s%s" \
         "%sDie Lösung war:%s%s"

# general hints about bot commands and such
mcset de "%sHint: %s" \
         "%sTip: %s"

mcset de "Game is paused." \
         "Das Quiz pausiert."

mcset de "Game is stopped." \
         "Das Quiz ist gestopt."

###########################################################################
#
# Messages regarding asked and asking questions (revolting, too)
#
###########################################################################

mcset de "%sSorry, my database is empty." \
         "%sSorry, meine Datenbank ist leer."

mcset de "Please stand by, the next question comes in less than %d seconds." \
         "Einen Moment, die nächste Frage komm in weniger als %d Sekunden."

#
# A larger set for the question header
#

mcset de "%s, open for %s:" \
         "%s, offen seit %s:"

mcset de "The level %s question no. %d by %s is worth %d points" \
         "Die Level %s Frage Nr. %d von %s (%d Punkte) ist"

mcset de "The level %s question no. %d by %s is" \
         "Die Stufe %s Frage Nr. %d von %s ist"

mcset de "The level %s question no. %d is worth %d points" \
         "Die Stufe %s Frage Nr. %d (%d Punkte) ist"

mcset de "The level %s question no. %d is" \
         "Die Stufe %s Frage Nr. %d ist"

mcset de "The level %s user question no. %d by %s is worth %d points" \
         "Die Stufe %s Userfrage Nr. %d von %s (%d Punkte) ist" 

mcset de "The level %s user question no. %d by %s is" \
         "Die Stufe %s Userfrage Nr. %d von %s ist"

mcset de "The level %s user question no. %d is worth %d points" \
         "Die Stufe %s Userfrage Nr. %d (%d Punkte) ist"

mcset de "The level %s user question no. %d is" \
         "Die Stufe %s Userfrage Nr. %d ist"

mcset de "The question no. %d by %s is worth %d points" \
         "Die Frage Nr. %d von %s (%d Punkte) ist"

mcset de "The question no. %d by %s is" \
         "Die Frage Nr. %d von %s ist"

mcset de "The question no. %d is worth %d points" \
         "Die Frage Nr. %d (%d Punkte) ist"

mcset de "The question no. %d is" \
         "Die Frage Nr. %d ist"

mcset de "The user question no. %d by %s is worth %d points" \
         "Die Userfrage Nr. %d von %s (%d Punkte) ist"

mcset de "The user question no. %d by %s is" \
         "Die Userfrage Nr. %d von %s ist"

mcset de "The user question no. %d is worth %d points" \
         "Die Userfrage Nr. %d (%d Punkte) ist"

mcset de "The user question no. %d is" \
         "Die Userfrage Nr. %d ist"


#
# !revolt
#
mcset de "does not react on revolts before at least one tip was given." \
         "reagiert nicht auf !revolt bevor wenigstens ein Tip gegeben wurde."

mcset de "Since you are revolting, you will be ignored for this question." \
         "Da Du widersprichst, wirst Du für diese Frage ignoriert."

mcset de "sees that %s and %d other dislike the question, you need %d people." \
         "sieht, dass %s und %d andere die Frage nicht mögen.  Ihr braucht %d Leute."

mcset de "will solve the question immediately." \
         "löst die Frage sofort auf."

#
# solved by bot or manually
#
mcset de "%sAutomatically solved after %s." \
         "%sAutomatisch aufgelöst nach %s."

mcset de "%sManually solved after %s by %s" \
         "%1\$sManuell aufgelöst von %3\$s nach %2\$s."

mcset de "%sThe answer is:%s%s" \
         "%sDie Lösung lautet:%s%s"

mcset de "%sAnd should match:%s%s" \
         "%sPassend auf:%s%s"

mcset de "%sHint %d:" \
         "%sTip %d:"

#
# userquestions
#

mcset de "Sorry, userquestions are disabled." \
         "Sorry, Userfragen sind deaktiviert."

mcset de "Sorry, you MUST be in the quizchannel to ask questions." \
         "Sorry, Du musst im quizchannel sein, um Userfragen zu stellen."

mcset de "Sorry, your userquest would trigger the badwords detection and will not be asked." \
        "Sorry, deine Userfrage würde das Badwords-Skript aktivieren und wird daher nicht gestellt."

mcset de "Sorry, there are already %d user questions scheduled.  Try again later." \
         "Sorry, es sind bereits %d Userfragen in der Warteschlange.  Probiers später nochmal."

mcset de " (regexp \"%s\")" \
         " (Regexp \"%s\")"

mcset de "Your quest \"%s\" is scheduled with answer \"%s\"%s and will be asked after %d questions." \
         "Deine Frage \"%s\" mit Antwort \"%s\"%s ist aufgenommen und kommt nach %d Fragen dran."

mcset de "Wrong number of parameters.  Use alike <question>::<answer>::<regexp>.  The regexp is optional and used with care." \
         "Falsche Anzahl von Parametern.  Syntax: <question>::<answer>::<regexp>.  Regexp ist optional für Experten."

mcset de "You said: \"%s\".  I recognize this as: \"%s\" and \"%s\", regexp: \"%s\"." \
         "Du sagtest: \"%s\".  Ich erkenne das als: \"%s\" und \"%s\", regexp: \"%s\"."

mcset de "No, only %s can give tips here!" \
         "Nur %s kann momentan Tips geben!"

mcset de "No usergame running." \
         "Das ist gerade keine Userfrage."

mcset de "Sorry, you MUST be in the quizchannel to give tips." \
         "Sorry, Du musst im Quizchannel sein, um Tips geben zu können."

mcset de "No, only %s can solve this question!" \
         "Nur %s kann diese Frage auflösen lassen!"

mcset de "No, only %s can cancel this question!" \
         "Nur %s kann diese Frage abbrechen!"

mcset de "Your question is canceled and will be solved." \
         "Deine Frage wird abgebrochen und aufglöst."

mcset de "Your question \"%s\" will be skipped." \
         "Deine Frage \"%s\" wird nicht gestellt."

mcset de "Sorry, the next question is by %s." \
         "Sorry, die nächste Frage ist von %s."


###########################################################################
#
# Help related stuff.  The help texts themselfes are in intl/XX/help.txt
#
###########################################################################


mcset de "Sorry, there is no help text loaded for the quiz." \
        "Sorry, es ist keine Hilfe zum Quiz geladen."

mcset de "Can't help you about '%s'.  Choose a topic from: %s" \
        "Kann zu '%s' nichts sagen.  Wähle ein Thema: %s"

# Help for MoxQuizz Version 0.8.0
mcset de "%s Help for %s version %s" \
        "%s Hilfe für %s Version %s"

###########################################################################
#
# Other messages concerning certain events (extra score, ...)
#
###########################################################################

#
# changing scores
#
mcset de "%s Setting score for the question to %d points (%+d)." \
         "%s Ändere Punkte für die Frage auf %d (%+d)."

mcset de "%s %s has new score %s<%d>%s (%+d) on rank %d." \
         "%s [botcolor boldtxt]Neuer Punktestand für %s: %s<%d>%s (%+d) auf Rang %d."

mcset de "%s  Set by %s." \
         "%s  Geändert von %s."

#
# requesting allstars and rank table
#
mcset de "Sorry, \"%s\" is not an acccepted number." \
         "Sorry, \"%s\" ist keine Zahl."

mcset de "%sRank list is empty." \
         "%sPunktetabelle ist leer."

mcset de "You requested too many lines, limiting to %d." \
         "Du verlangst zuviele Zeilen, beschränke auf %d."

mcset de "%sCurrent Top %d (game won at %d pts):" \
         "%sAktuelle Top %d (Spiel gewonnen bei %d Punkten):"

mcset de "%s* Congrats! *" \
         "%s* Gratulation! *"

# short for points
mcset de "pts" \
         "Pkte"

mcset de "%sRank started %s ago." \
         "%sDas Spiel läuft bereits %s."

mcset de "%sRanks reset by %s after %d questions." \
         "%1\$sPunktetabelle nach %3\$d Fragen von %2\$s gelöscht."

mcset de "%sAllstars list is empty." \
         "%sAllstars Liste ist leer."

mcset de "%sAll-Stars top %d:" \
         "%sAll-Stars Top %d:"

mcset de "games" \
         "Spiele"

mcset de "%sThere were %d users playing %d games." \
         "%s%d User haben %d Spiele gespielt."

mcset de "does not record you in the allstars table, since you played alone." \
         "nimmt dieses Spiel nicht in die Allstarstablle auf, da Du alleine gespielt hast."

mcset de "records %s with %5.3f points on the all-stars table (now %5.3f points, pos %d)." \
         "%s erhält %5.3f Punkte für die Allstarstabelle (jetzt %5.3f Punkte, pos %d)."

#
# Asking for current score
#

mcset de "%s accumulated %5.3f points in the all-stars table and keep position %d after %d games." \
         "%s hat %5.3f Punkte in der Allstars-Tabelle auf Rang %d nach %d Spielen."

mcset de "%s did not make any points in this game yet." \
         "%s hat in diesem Spiel noch keinen Punkt errungen."

mcset de "%s is not yet listed for the current game." \
         "%s hat in diesem Spiel noch keinen Ton von sich gegeben."

mcset de "%s made %d points and is on rank %d in the current game (%d more needed to win)." \
         "%s hat im aktuellen Spiel %d Punkte auf Rang %d (%d bis zum Gewinn)."

mcset de "%s not yet reached the all-stars table." \
         "%s hat es noch nicht in die Allstars-Tabelle geschafft."

mcset de "You accumulated %5.3f points in the all-stars table and keep position %d after %d games." \
         "Du hast %5.3f Punkte in der Allstars-Tebelle auf Rang %d nach %d Spielen."

mcset de "You are not yet listed for the current game." \
         "Du hast bisher noch keinen Rateversuch unternommen."

mcset de "You did not make any points in this game yet." \
         "Du hast im aktuellen Spiel noch keinen Punkt gemacht."

mcset de "You have not yet reached the all-stars table." \
         "Du hast es noch nicht in die Allstars-Tabelle geschafft."

mcset de "You made %d points and are on rank %d in the current game (%d more needed to win)." \
         "Du hast im aktuellen Spiel %d Punkte auf Rang %d (%d bis zum Gewinn)."

#
# !comments
#
mcset de "Your comment was logged." \
         "Deine Anmerkung wurde aufgezeichnet."

mcset de "Well, comment something *g*" \
         "Naja, _mach_ einen Kommentar *g*"

#
# !rules
#
mcset de "No rules loaded.  This doesn't mean there are no rules for this channel.  Beware!" \
         "Keine Regeln geladen.  Das heisst nicht, das es keine gibt.  Pass auf!"

mcset de "%s Rules for %s" \
         "%s Regeln für %s"

#
# Configuration changes
#
mcset de "%sScore to win set from %d to %d (%+d)." \
         "%sPunkte zum Gewinnen von %d auf %d (%+d) gesetzt."

#
# user changes nick
#
mcset de "Your old scores of %d were collected, since I know your host." \
         "Deine alten %d Punkte wurden aufgesammelt, da ich deinen Rechner wiedererkenne."

mcset de "Your host was new to me, old scores deleted." \
         "Dein Rechner ist neu für mich, alte Punkte gelöscht."

mcset de "I saw you renaming and transferred scores." \
         "Ok, Deine Punkte wurden auf den neuen Nick übertragen."

#
# user joins channel
#
mcset de "Welcome to %sversion %s, © by Moxon <moxon@meta-x.de>.  Say \"!ask\" to get the current question or \"!qhelp\" to get an help text." \
         "Willkommen zu %sVersion %s, © by Moxon <moxon@meta-x.de>.  Sag \"!ask\" um die aktuelle Frage zu erhalten oder \"!qhelp\" für den Hilfetext."

mcset de "%s  Check the channel rules with !rules." \
         "%s  Lies die Channelregeln mit !rules an."

mcset de "You are listed with %d points on rank %d." \
         "Du hast %d Punkte auf Rang %d."

mcset de "Your hostmask is new to me, deleting old scores." \
         "Deine hostmask ist mir neu, lösche alte Punkte."

mcset de "The current game is paused after %d questions." \
         "Das Spiel ist nach %d Fragen angehalten."

mcset de "There is a game running, %d questions have already been asked." \
         "Es läuft ein Spiel, %d Fragen wurden bereits gestellt."

mcset de "%s  I know about %d questions." \
         "%s  Meine Datenbank umfasst %d Fragen."

#
# stuff that didn't fit elsewhere
#
mcset de "Hi %s!  Nice to see you." \
         "Hi %s!  Schön Dich zu sehen."

mcset de "Thanks for playing ppl, I'll exit now (and thanks for all the fish)." \
         "Danke fürs Spiele, Leute.  Ich gehe jetzt (und Danke für den Fisch)."

mcset de "%s Channel found deserted." \
         "%s Hm, keiner spielt mehr."

mcset de "second" "Sekunde"
mcset de "seconds" "Sekunden"
mcset de "minute" "Minute"
mcset de "minutes" "Minuten"
mcset de "hour" "Stunde"
mcset de "hours" "Stunden"
mcset de "day" "Tag"
mcset de "days" "Tage"
mcset de "week" "Woche"
mcset de "weeks" "Wochen"
mcset de "month" "Monat"
mcset de "months" "Monate"

