###########################################################################
#
#  French translation of MoxQuizz' messages
#
#  Translator:  "Gun@gnoo.org" <Gunslinger@ifrance.com>
#
###########################################################################

###########################################################################
#
# Status messages
#
###########################################################################

#
# initialize
#
mcset fr "%sHello!  I am a MoxQuizz version %s and ready to squeeze your brain!" \
         "%sBonjour!  Je suis un  bot MoxQuizz version %s, prêt à te remuer les méninges !"

mcset fr "%s%d questions in database, just %s!ask%s.  Report bugs and suggestions to moxon@meta-x.de" \
         "%sIl y a %d questions dans la base de données, tape juste %s!ask%s. Rapport de bug(s) et suggestions : moxon@meta-x.de"

#
# stopped
#
mcset fr "%s %sQuiz stopped." \
         "%s %sQuiz terminé."

#
# paused
#
mcset fr "%s %sQuiz halted.  Say !ask for new questions." \
         "%s %sQuiz stoppé.  Tape !ask pour de nouvelles questions."

mcset fr "%sQuiz paused%s" \
         "%sPause du Quizz%s"

mcset fr " after %s." \
         " après %s."

#
# continue
#
mcset fr "%sQuiz continued.  Since there is no open question, a new one will be asked." \
         "%sLe Quizz reprend. Comme il n'y a pas de questions en cours, une nouvelle sera posée."

mcset fr "%sQuiz continued.  The question open since %s, worth %d point(s):" \
         "%sLe Quizz reprend.  Question posée depuis %s pour %d point(s):"

mcset fr "%sQuiz continued.  The user question open since %s, worth %d point(s):" \
         "%sLe Quizz reprend.  La question utilisateur posée depuis %s, pour %d points(s):"

#
# exit
#
mcset fr "%sI am leaving now, after running for %s."\
         "%sJe pars, après une présence de %s."

#
# Quiz moved to a new channel
#
mcset fr "Quiz is leaving to %s.  Goodbye!"\
         "Retrouvez moi sur %s.  A bientôt!"

mcset fr "Quiz is now on this channel.  Hello!" \
         "Salut ! Le Quizz est prêt pour ce chan !"

mcset fr "%s Goodbye." \
         "%s @+"


###########################################################################
#
# Messages regarding solved questions and such.
#
###########################################################################


mcset fr "%s: since you won %d games in a row, you will be ignored for the next game." \
        "%s: comme tu as remporté %d victoires a la suite, tu sera ignoré pour la prochaine partie."

mcset fr "No, you've won the last %d games." \
         "Non , Tu as remporté les %d dernières parties."

mcset fr "%s solved after %s and now has %s<%d>%s points (+%d) on rank %d." \
         "%s résolu après %s et a desormais %s<%d>%s points (+%d) classé à la place %d."

mcset fr "%sThe answer was:%s%s" \
         "%sLa réponse était:%s%s"

mcset fr "%sThree in a row!" \
         "%sTriple Victoire!"

mcset fr "%sCongratulation, five in a row! You receive an extra point." \
         "%sFelicitation ! Cinq victoires à la suite! Tu reçois un point de bonus."

mcset fr "%sTen in a row! This is really rare, so you get 3 extra points." \
         "%sIncroyable ! Dix victoires à la suite ! tu reçoit un bonus de 3 points  ."

mcset fr "%sTwenty in a row! This is extremely rare, so you get 5 extra points." \
         "%sDu jamais vu ! Vingt victoires à la suite ! Tu remporte un bonus de 5 points ."

mcset fr "%s%s reaches %d points and wins%s" \
         "%s%s atteint %d points et remporte la victoire%s"

mcset fr "%sHalftime.  Game is won at %d points." \
         "%sMi-Temps.  Le jeu prend fin à %d points."

mcset fr "%s%s has 10 points to go." \
         "%s%s est à 10 points de la victoire."

mcset fr "%s%s has 5 points to go." \
         "%s%s n'a plus 5 points à marquer avant de gagner."

mcset fr "%s%s has %d point(s) to go." \
         "%s%s est à %d de la victoire."

mcset fr "%s solved own question after %s and gets no points, keeping %s<%d>%s points on rank %d." \
         "%s a répondu a sa propre question après %s et ne remporte pas de points. Score:  %s<%d>%s Classement: %d."

mcset fr "%sThe answer was:%s%s" \
         "%sLa réponse était:%s%s"

# general hints about bot commands and such
mcset fr "%sHint: %s" \
         "%sConseil: %s"

mcset fr "Game is paused." \
         "Le jeu est en pause."

mcset fr "Game is stopped." \
         "Le jeu est terminé."

###########################################################################
#
# Messages regarding asked and asking questions (revolting, too)
#
###########################################################################

mcset fr "%sSorry, my database is empty." \
         "%sDésolé, ma base de donnée est vide."

mcset fr "Please stand by, the next question comes in less than %d seconds." \
         "Merci de patienter, la prochaine question arrive dans %d Secondes."

#
# A larger set for the question header
#

mcset fr "%s, open for %s:" \
         "%s, ouvert pour %s:"

mcset fr "The level %s question no. %d by %s is worth %d points" \
         "Niveau : %s question n° %d de %s pour %d points"

mcset fr "The level %s question no. %d by %s is" \
         "Niveau : %s question n° %d de %s :"

mcset fr "The level %s question no. %d is worth %d points" \
         "Niveau : %s question n° %d (%d points)"

mcset fr "The level %s question no. %d is" \
         "Niveau : %s Question n° %d :"

mcset fr "The level %s user question no. %d by %s is worth %d points" \
         "Niveau : %s Question utilisateur n° %d de %s pour %d points :" 

mcset fr "The level %s user question no. %d by %s is" \
         "Niveau : %s Question utilisateur n° %d de %s :"

mcset fr "The level %s user question no. %d is worth %d points" \
         "Niveau : %s Question utilisateur n° %d pour %d points :"

mcset fr "The level %s user question no. %d is" \
         "Niveau : %s Question utilisateur n° %d :"

mcset fr "The question no. %d by %s is worth %d points" \
         "Question n° %d de %s pour %d points"

mcset fr "The question no. %d by %s is" \
         "Question n° %d de %s :"

mcset fr "The question no. %d is worth %d points" \
         "Question n° %d pour %d points :"

mcset fr "The question no. %d is" \
         "Question n° %d :"

mcset fr "The user question no. %d by %s is worth %d points" \
         "Question utilisateur n° %d de %s pour %d points :"

mcset fr "The user question no. %d by %s is" \
         "Question utilisateur n° %d de %s :"

mcset fr "The user question no. %d is worth %d points" \
         "Question utilisateur n° %d pour %d points :"

mcset fr "The user question no. %d is" \
         "Question utilisateur n° %d :"


#
# !revolt
#
mcset fr "does not react on revolts before at least one tip was given." \
         "ne réagis pas a !revolt avant qu'au moins un indice ne soit donné."

mcset fr "Since you are revolting, you will be ignored for this question." \
         "Comme tu te revolte, tu sera ignoré pour cette question."

mcset fr "sees that %s and %d other dislike the question, you need %d people." \
         "contate que %s et %d autres personnes n'aiment pas la question.  Vous avez encore besoin de %d personnes."

mcset fr "will solve the question immediately." \
         "va resoudre la question immédiatement."

#
# solved by bot or manually
#
mcset fr "%sAutomatically solved after %s." \
         "%sRésolue automatiquement après %s."

mcset fr "%sManually solved after %s by %s" \
         "%sRésolue manuellement par %s après %s."

mcset fr "%sThe answer is:%s%s" \
         "%sLa réponse est:%s%s"

mcset fr "%sAnd should match:%s%s" \
         "%sEt doit correspondre:%s%s"

mcset fr "%sHint %d:" \
         "%sIndice %d:"

#
# userquestions
#

mcset fr "Sorry, userquestions are disabled." \
         "Désolé, les questions des utilisateurs sont désactivés."

mcset fr "Sorry, you MUST be in the quizchannel to ask questions." \
         "Désolé,mais vous DEVEZ être dans le chan de quizz pour répondre aux questions."

mcset fr "Sorry, your userquest would trigger the badwords detection and will not be asked." \
        "Désolé, ta question déclancherais la détection de badwords et ne sera donc pas posée."

mcset fr "Sorry, there are already %d user questions scheduled.  Try again later." \
         "Désolé,il y a déjà %d question de prévue.  Rééssaie plus tard."

mcset fr " (regexp \"%s\")" \
         " (Regexp \"%s\")"

mcset fr "Your quest \"%s\" is scheduled with answer \"%s\"%s and will be asked after %d questions." \
         "Ta question \"%s\" est programmée avec la réponse \"%s\"%s et sera posée après %d autres questions."

mcset fr "Wrong number of parameters.  Use alike <question>::<answer>::<regexp>.  The regexp is optional and used with care." \
         "Il manque un ou plusieurs paramètres.  Syntaxe: <question>::<réponse>::<regexp>.  regexp est optionnel ."

mcset fr "You said: \"%s\".  I recognize this as: \"%s\" and \"%s\", regexp: \"%s\"." \
         "Tu as dit: \"%s\".  Je reconnais ça comme: \"%s\" et \"%s\", regexp: \"%s\"."

mcset fr "No, only %s can give tips here!" \
         "Non, seul %s peut donner des indices ici!"

mcset fr "No usergame running." \
         "Pas de jeu utilisateur en cours."

mcset fr "Sorry, you MUST be in the quizchannel to give tips." \
         "Désolé, mais vous DEVEZ être dans le chan de quizz pour donner des conseils."

mcset fr "No, only %s can solve this question!" \
         "Non, seul %s peut résoudre cette question!"

mcset fr "No, only %s can cancel this question!" \
         "Non, seul %s peu annuler cette question!"

mcset fr "Your question is canceled and will be solved." \
         "Ta question a été annulée et ne sera pas résolue."

mcset fr "Your question \"%s\" will be skipped." \
         "Ta question \"%s\" sera passée."

mcset fr "Sorry, the next question is by %s." \
         "Désolé, la question suivante est de %s."


###########################################################################
#
# Help related stuff.  The help texts themselfes are in intl/XX/help.txt
#
###########################################################################


mcset fr "Sorry, there is no help text loaded for the quiz." \
        "Désolé, il n'y a pas de texte d'aide chargé pour le quizz."

mcset fr "Can't help you about '%s'.  Choose a topic from: %s" \
        "Je ne peut pas t'aider sur '%s' Choisi un sujet de: %s"

# Help for MoxQuizz Version 0.8.0
mcset fr "%s Help for %s version %s" \
        "%s Aide pour %s Version %s"

###########################################################################
#
# Other messages concerning certain events (extra score, ...)
#
###########################################################################

#
# changing scores
#
mcset fr "%s Setting score for the question to %d points (%+d)." \
         "%s Score de la question fixé à %d points (%+d)."

mcset fr "%s %s has new score %s<%d>%s (%+d) on rank %d." \
         "%s %s a un nouveau score %s<%d>%s (%+d) à la place %d."

mcset fr "%s  Set by %s." \
         "%s  Fixé par %s."

#
# requesting allstars and rank table
#
mcset fr "Sorry, \"%s\" is not an acccepted number." \
         "Désolé, \"%s\" n'est pas un nombre accepté."

mcset fr "%sRank list is empty." \
         "%sLe classement est vide."

mcset fr "You requested too many lines, limiting to %d." \
         "Tu demande trop de lignes, limitation fixée à %d."

mcset fr "%sCurrent Top %d (game won at %d pts):" \
         "%sTop %d actuel (Le jeu est remporté avec %d points):"

mcset fr "%s* Congrats! *" \
         "%s* Félicitations! *"

# short for points
mcset fr "pts" \
         "pts"

mcset fr "%sRank started %s ago." \
         "%sClassement commencé il y a %s."

mcset fr "%sRanks reset by %s after %d questions." \
         "%sClassement ré-initialisé par %s après %d questions."

mcset fr "%sAllstars list is empty." \
         "%sLa liste Allstars est vide."

mcset fr "%sAll-Stars top %d:" \
         "%sLe top %d All-Stars :"

mcset fr "games" \
         "parties"

mcset fr "%sThere were %d users playing %d games." \
         "%sIl y avait %d utilisateurs, qui ont joués %d parties."

mcset fr "does not record you in the allstars table, since you played alone." \
         "Je ne t'enregistre pas dans la table All-Stars, car tu as joué seul."

mcset fr "records %s with %5.3f points on the all-stars table (now %5.3f points, pos %d)." \
         "enregistré %s avec %5.3f points dans la table All-Stars (désormais %5.3f points, pos %d)."

#
# Asking for current score
#

mcset fr "%s accumulated %5.3f points in the all-stars table and keep position %d after %d games." \
         "%s a accumulé %5.3f points dans la table Allstars et garde la position %d après %d parties."

mcset fr "%s did not make any points in this game yet." \
         "%s n'a encore marqué aucun point dans la partie en cours."

mcset fr "%s is not yet listed for the current game." \
         "%s n'est pas encore listé pour le jeu en cours."

mcset fr "%s made %d points and is on rank %d in the current game (%d more needed to win)." \
         "%s a marqué %d points et se trouve à la place %d dans le jeu en cours (encore %d points pour gagner)."

mcset fr "%s not yet reached the all-stars table." \
         "%s n'a pas encore atteint la table All-Stars."

mcset fr "You accumulated %5.3f points in the all-stars table and keep position %d after %d games." \
         "Tu as accumulé %5.3f points dans la table All-Stars et garde la position %d après %d parties."

mcset fr "You are not yet listed for the current game." \
         "Tu n'est pas encore listé pour le jeu en cours."

mcset fr "You did not make any points in this game yet." \
         "Tu n'as encore marqué aucun point dans la partie en cours."

mcset fr "You have not yet reached the all-stars table." \
         "Tu n'as pas encore atteind la table All-Stars."

mcset fr "You made %d points and are on rank %d in the current game (%d more needed to win)." \
         "Tu as %d points et tu te trouve à la place %d dans le jeu en cours (encore %d points pour gagner )."

#
# !comments
#
mcset fr "Your comment was logged." \
         "Ton commentaire a été enregistré."

mcset fr "Well, comment something *g*" \
         "Bien, commente quelque chose *g*"

#
# !rules
#
mcset fr "No rules loaded.  This doesn't mean there are no rules for this channel.  Beware!" \
         "Pas de régles chargées. Cela ne signifie pas pour autant qu'il n'y en ai pas.  Attention!"

mcset fr "%s Rules for %s" \
         "%s Régles de %s"

#
# Configuration changes
#
mcset fr "%sScore to win set from %d to %d (%+d)." \
         "%sLe Score à atteindre pour gagner était de %d et a été fixé à %d (%+d)."

#
# user changes nick
#
mcset fr "Your old scores of %d were collected, since I know your host." \
         "Je reprend ton ancien score de %d points, comme je reconnais ton mask ."

mcset fr "Your host was new to me, old scores deleted." \
         "Ton host est nouveau pour moi, les vieux scores ont été effacés."

mcset fr "I saw you renaming and transferred scores." \
         "J'ai vu ton changement de nick et j'ai transféré les scores."

#
# user joins channel
#
mcset fr "Welcome to %sversion %s, © by Moxon <moxon@meta-x.de>.  Say \"!ask\" to get the current question or \"!qhelp\" to get an help text." \
         "Bienvenue au %sversion %s, © par Moxon <moxon@meta-x.de>.  Tape \"!ask\" pour avoir la question en cours ou \"!qhelp\" pour obtenir de l'aide."

mcset fr "%s  Check the channel rules with !rules." \
         "%s  Consulte les rêgles du chan avec !rules."

mcset fr "You are listed with %d points on rank %d." \
         "Tu a %d, à la place %d."

mcset fr "Your hostmask is new to me, deleting old scores." \
         "Ton mask est nouveau pour moi, J'efface les vieux scores."

mcset fr "The current game is paused after %d questions." \
         "Le jeu en cours est en pause après %d questions."

mcset fr "There is a game running, %d questions have already been asked." \
         "Un jeu est en cours, %d questions ont déjà été posées."

mcset fr "%s  I know about %d questions." \
         "%s  Je connais %d questions."

#
# stuff that didn't fit elsewhere
#
mcset fr "Hi %s!  Nice to see you." \
         "Bonjour %s!  Content de te voir."

mcset fr "Thanks for playing ppl, I'll exit now (and thanks for all the fish)." \
         "Merci à vous d'avoir joué. Je dois y aller (und Danke für den Fisch)."

mcset fr "%s Channel found deserted." \
         "%s Euuh..., le salon est vide."

mcset fr "second" "seconde"
mcset fr "seconds" "secondes"
mcset fr "minute" "minute"
mcset fr "minutes" "minutes"
mcset fr "hour" "heure"
mcset fr "hours" "heures"
mcset fr "day" "jour"
mcset fr "days" "jours"
mcset fr "week" "semaine"
mcset fr "weeks" "semaines"
mcset fr "month" "mois"
mcset fr "months" "mois"

