###########################################################################
#
#  Greek translation of MoxQuizz' messages
#
#  Translator:  "George Hadjithomas" <skaterz@cytanet.com.cy> (Bibib)
#
###########################################################################


###########################################################################
#
# Status messages
#
###########################################################################

#
# initialize
#
mcset gr "%sHello!  I am a MoxQuizz version %s and ready to squeeze your brain!" \
         "%sHello!  Eimai a MoxQuizz version %s kai etoimo na sas zouli3ei ta myala!"


mcset gr "%s%d questions in database, just %s!ask%s.  Report bugs and suggestions to moxon@meta-x.de" \
         "%s%d erotiseis se basi dedomenwn, apla %s!ask%s. Anaferete lathoi kai eisigiseis sto moxon@meta-x.de"


#
# stopped
#
mcset gr "%s %sQuiz stopped." \
         "%s %sQuiz stamatise."


#
# paused
#
mcset gr "%s %sQuiz halted.  Say !ask for new questions." \
         "%s %sTo Quiz stamatise. Grapsete !ask gia kainourgies erotiseis."


mcset gr "%sQuiz paused%s" \
         "%sQuiz ine se pausi%s"


mcset gr " after %s." \
         " meta %s."


#
# continue
#
mcset gr "%sQuiz continued.  Since there is no open question, a new one will be asked." \
         "%sSinexistike. Afou den iparxoun anixtes erotiseis, mia nea tha dothei tora."


mcset gr "%sQuiz continued.  The question open since %s, worth %d point(s):" \
         "%sSinexistike. I erotisi anixtike apo %s, a3ias %d vathmwn"


mcset gr "%sQuiz continued.  The user question open since %s, worth %d point(s):" \
         "%ssinexistike. O erotisi tou xristi anixtike apo %s, a3ias %d vathmwn"


#
# exit
#
mcset gr "%sI am leaving now, after running for %s."\
         "%sFevgw tora, afou imoun energos gia %s."


#
# Quiz moved to a new channel
#
mcset gr "Quiz is leaving to %s.  Goodbye!"\
         "Das To Quiz fevgei sto %s. Geia sas!"


mcset gr "Quiz is now on this channel.  Hello!" \
         "Das To Quiz ine tora se auto to kanali. Geia sas!"


mcset gr "%s Goodbye." \
         "%s Antio."


###########################################################################
#
# Messages regarding solved questions and such.
#
###########################################################################


mcset gr "%s: since you won %d games in a row, you will be ignored for the next game." \
        "%s: Afou nikises %d pexnidia stin seira, tha se agnow gia to epomeno pexnidi."


mcset gr "No, you've won the last %d games." \
         "Signomi, nikises ta teleutaia %d pexnidia."


mcset gr "%s solved after %s and now has %s<%d>%s points (+%d) on rank %d." \
         "%s elise meta apo %s kai tora exei %s<%d>%s vathmous (+%d) stin seira %d."


mcset gr "%sThe answer was:%s%s" \
         "%sI apantisi itan:%s%s"


mcset gr "%sThree in a row!" \
         "%sTria stin seira!"


mcset gr "%sCongratulation, five in a row! You receive an extra point." \
         "%sSigxaritiria, pente stin seira! Peires ena extra ponto."


mcset gr "%sTen in a row! This is really rare, so you get 3 extra points." \
         "%sDeka stin seira! Auto ine poli spanio, gia auto perneis 3 extra pontous."


mcset gr "%sTwenty in a row! This is extremely rare, so you get 5 extra points." \
         "%sEikosi stin seira! Auto ine para poly spanio, gia auto perneis 5 extra pontous."


mcset gr "%s%s reaches %d points and wins%s" \
         "%s%s eftase %d vathmous kai nika%s"


mcset gr "%sHalftime.  Game is won at %d points." \
         "%sImixrono. To pexnidi tha termatisei stous %d vathmous."


mcset gr "%s%s has 10 points to go." \
         "%s%s tou eminan 10 vathmoi."


mcset gr "%s%s has 5 points to go." \
         "%s%s tou eminan 5 vathmoi"


mcset gr "%s%s has %d point(s) to go." \
         "%s%s tou eminan %d vathmoi"


mcset gr "%s solved own question after %s and gets no points, keeping %s<%d>%s points on rank %d." \
         "%s elise tin diki tou erotisii meta apo %s kai den pernei vathmous, kratontas %s<%d>%s vathmous stin seira %d."


mcset gr "%sThe answer was:%s%s" \
         "%sI apantisi itan:%s%s"


# general hints about bot commands and such
mcset gr "%sHint: %s" \
         "%sKleidi voithia: %s"


mcset gr "Game is paused." \
         "To pexnidi ine se pausi."


mcset gr "Game is stopped." \
         "To pexnidi stamatise"


###########################################################################
#
# Messages regarding asked and asking questions (revolting, too)
#
###########################################################################

mcset gr "%sSorry, my database is empty." \
         "%sSignomi, I vasi dedomenwn ine adeia."


mcset gr "Please stand by, the next question comes in less than %d seconds." \
         "Parakalo perimenete, i epomeni erotisi tha erthei se ligotero apo %d deuterolepta."


#
# A larger set for the question header
#

mcset gr "%s, open for %s:" \
         "%s, Anixto gia %s:"

mcset gr "The level %s question no. %d by %s is worth %d points" \
         "Epipedo %s Erotisi noumero %d apo %s a3ias %d vathmwn"

mcset gr "The level %s question no. %d by %s is" \
         "Epipedo %s Erotisi noumero %d apo %s einai"

mcset gr "The level %s question no. %d is worth %d points" \
         "Epipedo %s Erotisi noumero %d einai a3ias %d vathmwn"

mcset gr "The level %s question no. %d is" \
         "Epipedo %s Erotisi noumero. %d einai"

mcset gr "The level %s user question no. %d by %s is worth %d points" \
         "Epipedo %s Erotisi xristi noumero. %d apo %s einai a3ias %d vathmwn" 

mcset gr "The level %s user question no. %d by %s is" \
         "Epipedo %s Erotisi tou xristi noumero. %d apo %s einai"

mcset gr "The level %s user question no. %d is worth %d points" \
         "Epipedo %s Erotisi tou xristi. %d einai a3ias %d vathmwn"

mcset gr "The level %s user question no. %d is" \
         "Epipedo %s Erotisi tou xristi. %d einai"

mcset gr "The question no. %d by %s is worth %d points" \
         "Erotisi noumero. %d apo %s einai a3ias %d vathmwn"

mcset gr "The question no. %d by %s is" \
         "Erotisi noumero. %d apo %s einai"

mcset gr "The question no. %d is worth %d points" \
         "Erotisi noumero. %d einai a3ias %d vathmwn"

mcset gr "The question no. %d is" \
         "Erotisi noumero. %d einai"

mcset gr "The user question no. %d by %s is worth %d points" \
         "Erotisi xristi noumero. %d apo %s einai a3ias %d vathmwn"

mcset gr "The user question no. %d by %s is" \
         "Erotisi xristi noumero. %d apo %s einai"

mcset gr "The user question no. %d is worth %d points" \
         "Erotisi xristi noumero. %d einai a3ias %d vathmwn"

mcset gr "The user question no. %d is" \
         "Erotisi xristi noumero. %d einai"


#
# !revolt
#
mcset gr "does not react on revolts before at least one tip was given." \
         "den antidra stin epiliseis, !revolt, prin dothei toulaxisto ena kleidi voithia."

mcset gr "Since you are revolting, you will be ignored for this question." \
         "afou diale3es na epiliseis tin erotisi, tha se agnoisw gia auti tin erotisi"

mcset gr "sees that %s and %d other dislike the question, you need %d people." \
         "vlepei oti %s kai %d alloi, den tous aresei i erotisi.  Xriazeste %d atoma."

mcset gr "will solve the question immediately." \
         "Tha epilisw tin erotisi amesos"

#
# solved by bot or manually
#
mcset gr "%sAutomatically solved after %s." \
         "%sEpilithike automata meta apo %s."

mcset gr "%sManually solved after %s by %s" \
         "%sEpilithike automata meta apo %s apo ton %s."

mcset gr "%sThe answer is:%s%s" \
         "%sI apantisi einai:%s%s"

mcset gr "%sAnd should match:%s%s" \
         "%sKai tha eprepe na teriazei:%s%s"

mcset gr "%sHint %d:" \
         "%sKleidi %d:"

#
# userquestions
#

mcset gr "Sorry, userquestions are disabled." \
         "Sorry, oi erotiseis tou xristi einai apenergopoiimenes"

mcset gr "Sorry, you MUST be in the quizchannel to ask questions." \
         "Sorry, prepei na ise se kanali quiz gia na rotiseis tis erotiseis sou"

mcset gr "Sorry, your userquest would trigger the badwords detection and will not be asked." \
        "Signomi, i erotisi sou tha energopoiouse tin tin euresi aisxrwn le3ewn kai den tha erotithei"

mcset gr "Sorry, there are already %d user questions scheduled.  Try again later." \
         "Sorry, iparxoun eidi %d erotiseis xristwn programmatismenes.  Dokimase 3ana argotera."

mcset gr " (regexp \"%s\")" \
         " (Regexp \"%s\")"

mcset gr "Your quest \"%s\" is scheduled with answer \"%s\"%s and will be asked after %d questions." \
         "I erotisi sou \"%s\" einai programmatismeni me apantisi \"%s\"%s kai tha rotithei meta apo %d erotiseis."

mcset gr "Wrong number of parameters.  Use alike <question>::<answer>::<regexp>.  The regexp is optional and used with care." \
         "Lanthasmenos arithmos parametrwn.  Xrisimopoia: <question>::<answer>::<regexp>. To Regexp einai proeretiko kai xrisimopoiitai me frontida."

mcset gr "You said: \"%s\".  I recognize this as: \"%s\" and \"%s\", regexp: \"%s\"." \
         "Eipes: \"%s\".  Ego to anagnorizw os: \"%s\" kai \"%s\", regexp: \"%s\"."

mcset gr "No, only %s can give tips here!" \
         "Oxi, mono %s mporei na dosei kleidia edo!"

mcset gr "No usergame running." \
         "Den trexei pexnidi xristi."

mcset gr "Sorry, you MUST be in the quizchannel to give tips." \
         "Sorry, prepei na ise se kanali quiz gia na doseis kleidia."

mcset gr "No, only %s can solve this question!" \
         "Oxi, mono %s mporei na epilisei tin erotisi!"

mcset gr "No, only %s can cancel this question!" \
         "Oxi, mono %s mporei na akirosei auti tin erotisi!"

mcset gr "Your question is canceled and will be solved." \
         "I erotisi exei akyrothei kai tha epilithei."

mcset gr "Your question \"%s\" will be skipped." \
         "I erotisi sou \"%s\" tha tin afiso pisw."

mcset gr "Sorry, the next question is by %s." \
         "Sorry, i epomeni erotisi einai apo %s."


###########################################################################
#
# Help related stuff.  The help texts themselfes are in intl/XX/help.txt
#
###########################################################################


mcset gr "Sorry, there is no help text loaded for the quiz." \
        "Sorry, den iparxei voithia text fortomeno gia to quiz."

mcset gr "Can't help you about '%s'.  Choose a topic from: %s" \
        "Dem mporw na voithiso gia '%s'.  Diale3e ena thema apo: %s"

# Help for MoxQuizz Version 0.8.0
mcset gr "%s Help for %s version %s" \
        "%s Voithima gia %s Version %s"

###########################################################################
#
# Other messages concerning certain events (extra score, ...)
#
###########################################################################

#
# changing scores
#
mcset gr "%s Setting score for the question to %d points (%+d)." \
         "%s Kanonizw tin vathmologia gia tin erotisi se %d vathmous (%+d)."

mcset gr "%s %s has new score %s<%d>%s (%+d) on rank %d." \
         "%s Exei nea vathmologia %s: %s<%d>%s (%+d) stin seira %d."

mcset gr "%s  Set by %s." \
         "%s  Topothetithike apo %s."

#
# requesting allstars and rank table
#
mcset gr "Sorry, \"%s\" is not an acccepted number." \
         "Sorry, \"%s\" den ine apodextos arithmos."

mcset gr "%sRank list is empty." \
         "%sI lista seiras einai adeia."

mcset gr "You requested too many lines, limiting to %d." \
         "Zitises polles grammes, periorizo se %d."

mcset gr "%sCurrent Top %d (game won at %d pts):" \
         "%sProsorino Top %d (to pexnidi tellionei stous %d vathmous):"

mcset gr "%s* Congrats! *" \
         "%s* Sigxaritiria! *"

# short for points
mcset gr "pts" \
         "Vathmoi"

mcset gr "%sRank started %s ago." \
         "%sSeira arxise prin %s."

mcset gr "%sRanks reset by %s after %d questions." \
         "%sSeires midenistikan apo ton/tin %s meta apo %d erotiseis"

mcset gr "%sAllstars list is empty." \
         "%sI lista Allstars einai adeia "

mcset gr "%sAll-Stars top %d:" \
         "%sAll-Stars Top %d:"

mcset gr "games" \
         "Pexnidia"

mcset gr "%sThere were %d users playing %d games." \
         "%s Ipir3an %d xristes pou epe3an %d pexnidia."

mcset gr "does not record you in the allstars table, since you played alone." \
         "den se vazei stin lista allstars, afou epezes monos/moni sou "

mcset gr "records %s with %5.3f points on the all-stars table (now %5.3f points, pos %d)." \
         "Kataxorithikan %s me %5.3f vathmous gia tin lista tou allstars (tora %5.3f vathmoi pos %d)."

#
# Asking for current score
#

mcset gr "%s accumulated %5.3f points in the all-stars table and keep position %d after %d games." \
         "%s mazeutikan %5.3f vathmoi stin lista tou allstars kai krata thesi %d meta apo %d pexnidia."

mcset gr "%s did not make any points in this game yet." \
         "%s den exei kanei akoma vathmous sto pexnidi."

mcset gr "%s is not yet listed for the current game." \
         "%s den ine akoma stin lista gia to paron pexnidi."

mcset gr "%s made %d points and is on rank %d in the current game (%d more needed to win)." \
         "%s ekane %d vathmous kai ine stin %d seira sto paron pexnidi (%d akoma gia na nikisei)."

mcset gr "%s not yet reached the all-stars table." \
         "%s den eftase akoma tin lista allstars."

mcset gr "You accumulated %5.3f points in the all-stars table and keep position %d after %d games." \
         "Mazepses %5.3f vathmous stin lista allstars, kai kratas thesi %d meta apo %d pexnidia."

mcset gr "You are not yet listed for the current game." \
         "Den exeis akoma mpei stin lista gia to paron pexnidi."

mcset gr "You did not make any points in this game yet." \
         "Den exeis kanei vathmous gia auto to pexnidi akoma."

mcset gr "You have not yet reached the all-stars table." \
         "Den exeis ftasei akoma tin lista allstars."

mcset gr "You made %d points and are on rank %d in the current game (%d more needed to win)." \
         "Ekanes %d vathmous kai ise stin seira %d gia to paron pexnidi (%d akoma gia na nikiseis)."

#
# !comments
#
mcset gr "Your comment was logged." \
         "To sxolio sou exei filaxthei."

mcset gr "Well, comment something *g*" \
         "Well, pes kati *g*"

#
# !rules
#
mcset gr "No rules loaded.  This doesn't mean there are no rules for this channel.  Beware!" \
         "Den exoun fortothei oi kanonismoi. Auto den simenei pos den iparxoun kanonismoi gia auto to kanali. Prosexete!"

mcset gr "%s Rules for %s" \
         "%s Kanonismoi gia %s"

#
# Configuration changes
#
mcset gr "%sScore to win set from %d to %d (%+d)." \
         "%sVathmologia gia na nikisete kanonistike apo %d se %d (%+d)."

#
# user changes nick
#
mcset gr "Your old scores of %d were collected, since I know your host." \
         "I pallia sou vathmologia twn %d exei mazeutei, afou 3ero to host sou."

mcset gr "Your host was new to me, old scores deleted." \
         "To host sou einai neo se emena, oles sou oi vathmologies exoun svistei."

mcset gr "I saw you renaming and transferred scores." \
         "Ok, eida oti alla3es onoma kai metefera tin vathmologia."

#
# user joins channel
#
mcset gr "Welcome to %sversion %s, © by Moxon <moxon@meta-x.de>.  Say \"!ask\" to get the current question or \"!qhelp\" to get an help text." \
         "Kalosorisete sto %sversion %s, © by Moxon <moxon@meta-x.de>.  Grapsete \"!ask\" gia na piasete tin paron erotisi i grapsete \"!qhelp\" Gia na piasete to voithima, help txt."

mcset gr "%s  Check the channel rules with !rules." \
         "%s  Deite tous kanonismous tou kanaliou grafontas !rules."

mcset gr "You are listed with %d points on rank %d." \
         "Exeis mpei stin lista me %d vathmous stin seira %d."

mcset gr "Your hostmask is new to me, deleting old scores." \
         "To hostmask sou ine kainourgio se eman, svinw oles sou tis pallies vathmologies."

mcset gr "The current game is paused after %d questions." \
         "To paron pexnidi exei mpei se pausi meta apo %d erotiseis."

mcset gr "There is a game running, %d questions have already been asked." \
         "Iparxei pexnidi pou trexei eidi, dothikan eidi %d erotiseis."

mcset gr "%s  I know about %d questions." \
         "%s  3ero peripou %d erotiseis."

#
# stuff that didn't fit elsewhere
#
mcset gr "Hi %s!  Nice to see you." \
         "Hi %s!  Xeromai pou se vlepw."

mcset gr "Thanks for playing ppl, I'll exit now (and thanks for all the fish)." \
         "Euxaristo pou pe3ate.  Tha figw tora."

mcset gr "%s Channel found deserted." \
         "%s To kanali vrethike erimo."

mcset gr "second" "Deuterolepto"
mcset gr "seconds" "Deuterolepta"
mcset gr "minute" "Lepto"
mcset gr "minutes" "lepta"
mcset gr "hour" "ora"
mcset gr "hours" "ores"
mcset gr "day" "mera"
mcset gr "days" "meres"
mcset gr "week" "evdomada"
mcset gr "weeks" "evdomades"
mcset gr "month" "minas"
mcset gr "months" "mines"
